version: '3.8'
services:
    app:
        container_name: markets
        command: node -r esm bin/start.js
        build:
            context: '.'
            dockerfile: './docker/Dockerfile'
        depends_on:
            - db
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - PORT=${PORT}
            - ETHPLORER_API_KEY=${ETHPLORER_API_KEY}
    db:
        container_name: postgres
        image: postgres:12-alpine
        ports:
            - '5432:5432'
        volumes:
            - markets-postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: markets
volumes:
      markets-postgres-data:
